workflows:
  my-workflow:
    name: Build Flutter app
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.ipa
